[images]
  remote_images = [
    "https://images.unsplash.com/.*",
    "https://randomuser.me/.*"
  ]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
